### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by codespop** [ihmpdcc/hmp_client#7]
I've tried to make it work using Chiron, but when I run `$ ./bin/hmp_client_interactive` it says `-bash: $: command not found` even though Chiron is successful installed and I'm in the directory. 

This is how the folder looks:

```
LICENSE		bin		docs		hmp_client	tests
README.md	docker		examples	pipelines
```

I then also tried `$ docker build . -t python_src` but it says `-bash: $: command not found
` again. 

Could you please offer some assistance?

**Comment by victor73** [comment]
It appears that the machine you tried to execute those commands on did not have docker installed. Did you try to run hmp_client_interactive on an Amazon instance of Chiron running in the cloud? Or did you run the git clone and hmp_client_interactive invocation on another machine or VM?

**Comment by jonathancrabtree** [comment]
Hi @codespop, it looks like maybe you're typing the dollar sign that represents the command prompt ("$") as part of the command itself. Instead of typing "$ ./bin/hmp_client_interactive", try simply "./bin/hmp_client_interactive" (the text _inside_ the quotes, that is). Likewise with the second command, instead of typing "$ docker build . -t python_src", try typing "docker build . -t python_src"   The "$" in the documentation represents the Linux/Unix command prompt and is there to indicate that the text _following_ the "$" may be entered as a command on the command line.

Note that the bash error message ("bash: $: command not found") tells us that the shell (bash) is complaining because it can't find a command called "$". Let us know if you have better luck (or at least a different error message!) after removing the "$" from your commands.

**Comment by codespop** [comment]
Thanks. It seems the docker daemon is not running -when I run the first command you wrote, I get: 

```
Docker image v1.1.5 for the HMP Client not found.  Downloading first ...
Saving files to /output in this Docker image will make them available in /Users/sofia/chiron/hmp_client outside of it.
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
```

Do you have some suggestions for counteracting this?

**Comment by jonathancrabtree** [comment]
Now I think Victor's earlier comment (and question) are applicable. Are you on an Amazon instance of Chiron running in the cloud, or did you run the git clone and subsequent commands on another machine or VM?

**Comment by codespop** [comment]
I have been able to get docker and the hmp client running. 
However, I am not sure how to make use of the .tsv files? I have downloaded them from the HMP Portal. 

```
MacBook-Pro:Chiron users$ ./bin/hmp_client_interactive
Docker image v1.1.5 for the HMP Client not found.  Downloading first ...
Saving files to /output in this Docker image will make them available in /users/chiron/hmp_client outside of it.
root@2d42d1e759a9:/# 
```
I have the manifest file stored in the Chiron folder.

When I try the example command with a re-directed folder, it doesn't work. How do I begin the process?

**Comment by victor73** [comment]
@codespop Can you please copy paste the exact command  you're trying and what the error message (if any) is?

**Comment by victor73** [comment]
Closing issue.
